package com.spring.dynamodb.sass.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@RequiredArgsConstructor
@DynamoDBTable(tableName = "Users")
public class User {
	@DynamoDBHashKey(attributeName = "userId")
	@DynamoDBAutoGeneratedKey
	private String userId;

	@DynamoDBAttribute(attributeName = "userName")
	private String username;
}
