package com.demo.dynamodb.entities.user;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

import java.util.Date;

//@Data
@DynamoDBTable(tableName = "user")
public class User {

	@Id
	//@Getter(AccessLevel.NONE)
	//@Setter(AccessLevel.NONE)
	private UserId userPrimaryKey;

	//@DynamoDBHashKey(attributeName = "userId")
	//private String userId;
	//
	//@DynamoDBRangeKey(attributeName = "updatedAt")
	//private Date updatedAt;

	//@DynamoDBAttribute(attributeName = "createdAt")
	//private Date createdAt;

	public User() {
	}

	public User(UserId userKey) {
		this.userPrimaryKey = userKey;
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "userId")
	public String getUserId() {
		return userPrimaryKey != null ? userPrimaryKey.getUserId() : null;
	}

	public void setUserId(String userId) {
		if (userPrimaryKey == null) {
			userPrimaryKey = new UserId();
		}
		userPrimaryKey.setUserId(userId);
	}

	@DynamoDBRangeKey(attributeName = "updatedAt")
	public Date getUpdatedAt() {
		return userPrimaryKey != null ? userPrimaryKey.getUpdatedAt() : null;
	}

	public void setUpdatedAt(Date updatedAt) {
		if (userPrimaryKey == null) {
			userPrimaryKey = new UserId();
		}
		userPrimaryKey.setUpdatedAt(updatedAt);
	}

	//@DynamoDBAttribute(attributeName = "userName")
	//private String username;
	//
	//@DynamoDBAttribute(attributeName = "email")
	//private String email;
	//
	//@DynamoDBAttribute(attributeName = "verified")
	//private Boolean isVerified;
	//
	//@DynamoDBAttribute(attributeName = "role")
	//private Set<String> role;
	//
	//@DynamoDBAttribute(attributeName = "companyId")
	//private String companyId;
}
