package com.demo.dynamodb.entities.user;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.springframework.data.annotation.Id;

import java.util.Date;
import java.util.Set;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "user")
public class User {

	@Id
	@Getter(AccessLevel.NONE)
	@Setter(AccessLevel.NONE)
	private UserCompositeKey userCompositeKey;

	@DynamoDBAttribute(attributeName = "updatedAt")
	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	private Date updatedAt;

	@DynamoDBAttribute(attributeName = "userName")
	private String username;

	@DynamoDBAttribute(attributeName = "email")
	private String email;

	@DynamoDBAttribute(attributeName = "verified")
	private Boolean isVerified;

	@DynamoDBAttribute(attributeName = "role")
	private Set<String> role;

	@DynamoDBAttribute(attributeName = "companyId")
	private String companyId;

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "userId")
	public String getUserId() {
		return userCompositeKey != null ? userCompositeKey.getUserId() : null;
	}

	@DynamoDBRangeKey(attributeName = "createdAt")
	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	public Date getCreatedAt() {
		return userCompositeKey != null ? userCompositeKey.getCreatedAt() : null;
	}

	public void setUserId(String userId) {
		if (userCompositeKey == null) {
			userCompositeKey = new UserCompositeKey();
		}
		userCompositeKey.setUserId(userId);
	}

	public void setCreatedAt(Date createdAt) {
		if (userCompositeKey == null) {
			userCompositeKey = new UserCompositeKey();
		}
		userCompositeKey.setCreatedAt(createdAt);
	}
}
