package com.demo.dynamodb.entities.user;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;

//@Getter
//@Setter
public class UserId implements Serializable {
	private static final long serialVersionUID = 1L;

	//@DynamoDBHashKey(attributeName = "userId")
	//@DynamoDBAutoGeneratedKey
	private String userId;

	//@DynamoDBRangeKey(attributeName = "updatedAt")
	private Date updatedAt;

	public UserId() {
		this(null, null);
	}

	public UserId(String userId, Date updatedAt) {
		this.userId = userId;
		this.updatedAt = updatedAt;
	}

	@DynamoDBHashKey
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@DynamoDBRangeKey
	public Date getUpdatedAt() {
		return updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}

