spring:
    profiles:
        active: dev
    data:
        dynamodb:
            entity2ddl:
                auto: create-only
                gsiProjectionType: ALL

aws:
    dynamodb:
        region: localhost
        endpoint: http://localhost:8000/
        accesskey: fakeKey
        secretkey: fakeKey2
