package com.demo.dynamodb.entities.company;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "company")
public class Company {

	@DynamoDBHashKey(attributeName = "companyId")
	@DynamoDBAutoGeneratedKey
	private String companyId;

	@DynamoDBAttribute(attributeName = "companyName")
	private String companyName;

	@DynamoDBAttribute(attributeName = "address")
	private String address;

	@DynamoDBAttribute(attributeName = "country")
	private String country;

	@DynamoDBAttribute(attributeName = "city")
	private String city;

	@DynamoDBAttribute(attributeName = "url")
	private String url;

	@DynamoDBAttribute(attributeName = "introduction")
	private String introduction;

	@DynamoDBAttribute(attributeName = "businessNumber")
	private String businessNumber;
}
