package com.demo.dynamodb.entities.company;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "company")
public class Company {

	@DynamoDBHashKey(attributeName = "companyId")
	@DynamoDBAutoGeneratedKey
	private String companyId;

	//@DynamoDBRangeKey(attributeName = "updatedAt")
	//private Date updatedAt;

	@DynamoDBAttribute(attributeName = "createdAt")
	private Date createdAt;

	@DynamoDBAttribute(attributeName = "companyName")
	private String companyName;

	@DynamoDBAttribute(attributeName = "address")
	private String address;

	@DynamoDBAttribute(attributeName = "country")
	private String country;

	@DynamoDBAttribute(attributeName = "city")
	private String city;

	@DynamoDBAttribute(attributeName = "url")
	private String url;

	@DynamoDBAttribute(attributeName = "introduction")
	private String introduction;

	@DynamoDBAttribute(attributeName = "businessNumber")
	private String businessNumber;
}
